/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLink: typeof import('./../components/AppLink/index.vue')['default']
    AppMain: typeof import('./../layout/components/AppMain/index.vue')['default']
    Breadcrumb: typeof import('./../components/Breadcrumb/index.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Hamburger: typeof import('./../components/Hamburger/index.vue')['default']
    IEpClose: typeof import('~icons/ep/close')['default']
    LangSelect: typeof import('./../components/LangSelect/index.vue')['default']
    NavBar: typeof import('./../layout/components/NavBar/index.vue')['default']
    NavBarLeft: typeof import('./../layout/components/NavBar/components/NavBarLeft.vue')['default']
    NavBarRight: typeof import('./../layout/components/NavBar/components/NavBarRight.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./../layout/components/Settings/index.vue')['default']
    SideBar: typeof import('./../layout/components/SideBar/index.vue')['default']
    SidebarLogo: typeof import('./../layout/components/SideBar/components/SidebarLogo.vue')['default']
    SidebarMenu: typeof import('./../layout/components/SideBar/components/SidebarMenu.vue')['default']
    SidebarMenuItem: typeof import('./../layout/components/SideBar/components/SidebarMenuItem.vue')['default']
    SidebarMenuItemTitle: typeof import('./../layout/components/SideBar/components/SidebarMenuItemTitle.vue')['default']
    SidebarMixTopMenu: typeof import('./../layout/components/SideBar/components/SidebarMixTopMenu.vue')['default']
    SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
    TagsView: typeof import('./../layout/components/TagsView/index.vue')['default']
  }
}
